config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :friends
    end
    member do
      get :feed
      patch :send_friend_request
    end
  end

  resources :locations do
    collection do
      get :near_me
    end
    member do
      patch :check_in
    end
  end

  resources :indoor_locations

  resources :check_ins

  resources :statistics

  resources :events do
    member do
      post :send_event_invite
      patch :rsvp
    end
  end

  resources :friend_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :invites do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :ratings do
    member do
      patch :upvote
      patch :downvote
    end
  end

  root to: 'users#feed'
end

app/models/invite.rb
class Invite < ActiveRecord::Base

  self.primary_keys = :user_id, :event_id

  belongs_to :event
  belongs_to :user

  enum rsvp: {no_response: 0, accepted: 1, rejected: 2}
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def index
    @Invites = Invite.where(user_id: session[:cas_user])
  end

  def accept
    invite = Invite.where(user_id: params[:user_id], event_id: params[:event_id]).first
    if invite.present?
      invite.rsvp = "accepted"
      invite.save
    end
    redirect_to :back
  end

 def decline
    invite = Invite.where(user_id: params[:user_id], event_id: params[:event_id]).first
    if invite.present?
      invite.rsvp = "rejected"
      invite.save
    end
    redirect_to :back
  end

end

app/views/invites/index.html.erb
<%=content_tag :h1, "Pending Invitations"%>

<%=content_tag :table, class: "colored" do%>
  <%=content_tag :thead do%>
    <%=content_tag :tr do%>
      <%=content_tag :th, "Location"%>
      <%=content_tag :th, "Time"%>
      <%=content_tag :th, "Status"%>
      <%=content_tag :th, ""%>
    <%end%>
  <%end%>

  <%=content_tag :tbody do%>
    <%@Invites.each do |invite|%>
      <%=content_tag :tr do%>
        <%=content_tag :td, link_to(invite.event.location.description, location_path(invite.event.location))%>
        <%=content_tag :td, link_to(invite.event.time, event_path(invite.event))%>
        <%if invite.accepted?%>
          <%=content_tag :td, "Going"%>
        <%else%>
          <%=content_tag :td, link_to("Going", accept_invite_path({id:0, user_id: session[:cas_user], event_id: invite.event_id}), {method: :patch})%>
        <%end%>
        <%if invite.rejected?%>
          <%=content_tag :td, "Not Going"%>
        <%else%>
          <%=content_tag :td, link_to("Not Going", decline_invite_path({id:0, user_id: session[:cas_user], event_id: invite.event_id}), {method: :patch})%>
        <%end%>
      <%end%>
    <%end%>
  <%end%>
<%end%>