config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :friends
    end
    member do
      get :feed
      patch :send_friend_request
    end
  end

  resources :locations do
    collection do
      get :near_me
    end
    member do
      patch :check_in
    end
  end

  resources :indoor_locations

  resources :check_ins

  resources :statistics

  resources :events do
    member do
      post :send_event_invite
      patch :rsvp
    end
  end

  resources :friend_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :invites do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :ratings do
    member do
      patch :upvote
      patch :downvote
    end
  end

  root to: 'users#feed'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :location
  has_many :invites
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    search = []
    search_params = {}

    if params[:time].present? && params[:time][:filter].present?
      search << "time < :time"
      search_params.merge! time: "#{params[:time][:filter].to_f.hours.from_now}"
      search << "time > :time_now"
      search_params.merge! time_now: "#{Time.now}"
    end

    if params[:location].present? && params[:location][:filter].present?
      search << "description like :description"
      search_params.merge! description: "%#{params[:location][:filter]}%"
    end

    if params[:only_rsvp].present? && params[:only_rsvp]
      @events = Event.joins(:invites).where('invites.user_id' => session[:cas_user], 'invites.rsvp' => Invite.rsvps[:accepted]).joins(:location).where(search.join(' AND '), search_params).order(time: :desc)
    else
      @events = Event.joins(:location).where(search.join(' AND '), search_params)
    end
  end

  def show
    @event = Event.find(params[:id])
    @invites = Invite.where(event_id: params[:id], rsvp: Invite.rsvps[:accepted])

    @my_rsvp = Invite.where(event_id: params[:id], user_id: session[:cas_user]).first
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      redirect_to event_path(@event)
    else
      render action: :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator_id = session[:cas_user]
    if @event.save
      # The event's creator will have an RSVP to the event by default.
      creator_rsvp = Invite.new(user_id: session[:cas_user], event_id: @event.id, rsvp: Invite.rsvps[:accepted])
      creator_rsvp.save

      redirect_to event_url(@event)
    else
      render action: :new
    end
  end

  def destroy
    Event.transaction do
      Invite.destroy(event_id: params[:id])
      Event.find(params[:id]).destroy
    end
    
    redirect_to events_url
  end

  def send_event_invite
    event = params[:id]
    rsvp = Invite.rsvps[:no_response]
    user = params[:case_id]

    users = User.where(user_id: user)

    if Invite.where(user_id: user, event_id: event).blank? && !users.blank?
      request = Invite.new(user_id: user, event_id: event, rsvp: rsvp)
      request.save
    elsif(users.blank?)
      flash[:notice] = 'No user with that ID'
    end

    redirect_to :back
  end

  def rsvp
    event = params[:id]
    rsvp = Invite.rsvps[:accepted]
    user = session[:cas_user]

    rsvp = Invite.new(user_id: user, event_id: event, rsvp: rsvp)
    rsvp.save

    redirect_to :back
  end

  private

  def event_params
    params.require(:event).permit(:id, :time, :location_id)
  end

end

app/views/events/_form.html.erb
<%=content_tag :table, class: "key-value" do%>

  <%=content_tag :tr do%>
    <%=content_tag :th do%>
      <%=form.label :time, "Time:"%>
    <%end%>
    <%=content_tag :td do%>
      <%=form.text_field :time, id: "datetimepicker"%>
    <%end%>
  <%end%>

  <%=content_tag :tr do%>
    <%=content_tag :th do%>
      <%=form.label :location_id, "Location:"%>
    <%end%>
    <%=content_tag :td do%>
      <%=form.select :location_id, options_for_select(Location.selectable_list, @event.location_id), {include_blank: true}%>
    <%end%>
  <%end%>
<%end%>

<%=javascript_tag do%>

  $('#datetimepicker').datetimepicker();

<%end%>

app/views/events/_friends_events.html.erb
<!-- The following partial is being organized into a table to allow for CSSing per row. -->
<%=content_tag :table, class: "colored" do%>
  <%@events.each do |event|%>
    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=(create_verbose_name_list(event) +
           " going to " +
           link_to(event.location.description, location_path(event.location)) +
           " at " +
           link_to(event.time.strftime("%l:%M%p on %m/%d/%Y"), event)).html_safe%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

app/views/events/edit.html.erb
<%=content_tag :h1, "Edit Event"%>

<%=form_for(@event) do |form| %>
  <%=content_tag :table do%>
    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=render partial: 'form', locals:{form:form}%>
      <%end%>
    <%end%>
    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=submit_tag "Update"%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

app/views/events/index.html.erb
<%=content_tag :h1, "Events"%>

<%=form_tag events_path, method: :get do%>
  <%=label_tag :time_filter, "Hours from now: "%>
  <%=text_field :time, :filter, value: params[:time].try(:[], :filter)%>

  <%=label_tag :location_filter, "Location Description: "%>
  <%=text_field :location, :filter, value: params[:location].try(:[], :filter)%>

  <%=label_tag :location_filter, "Only Events I've RSVPed to: "%>
  <%=check_box_tag :only_rsvp, 1, params[:only_rsvp] %>

  <%=submit_tag "Search", id: "search"%>
<%end%>

<%=content_tag :table, class: "colored" do%>
  <%=content_tag :thead do%>
    <%=content_tag :tr do %>
      <%=content_tag :th, "Time"%>
      <%=content_tag :th, "Location"%>
    <%end%>
  <%end%>
  <%=content_tag :tbody do%>
    <%@events.each do |event|%>
      <%=content_tag :tr do%>
        <%=content_tag :td, link_to(event.time, event_path(event.id))%>
        <%=content_tag :td, link_to(event.location.description, location_path(event.location_id))%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

<%=link_to "Create new event", new_event_path%>

app/views/events/new.html.erb
<%=content_tag :h1, "New Event"%>

<%=form_for(@event) do |form| %>
  <%=content_tag :table do%>
    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=render partial: 'form', locals:{form:form}%>
      <%end%>
    <%end%>
    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=submit_tag "Create"%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

app/views/events/show.html.erb
<%=content_tag :h1, "View Event"%>
<%=content_tag :table, class: "key-value" do%>
  <%=content_tag :tr do%>
    <%=content_tag :th, "When"%>
    <%=content_tag :td, @event.time%>
  <%end%>

  <%=content_tag :tr do%>
    <%=content_tag :th, "Where"%>
    <%=content_tag :td, link_to(@event.location.description, location_path(@event.location.id))%>
  <%end%>
<%end%>


<%if session[:cas_user] == @event.creator_id%>
  <%=link_to "Edit", edit_event_path(@event)%>
  <%=tag(:br)%>
  <%=link_to "Delete", event_path(@event), data: {confirm: 'Really delete this event?'}, method: :delete%>
  <%=tag(:br)%>
<%end%>

<%=content_tag :h3, "Users Going"%>
<%=content_tag :table do%>
  <%@invites.each do |invite|%>
    <%=content_tag :tr do%>
      <%=content_tag :td, link_to(invite.user.name, user_path(invite.user_id))%>
    <%end%>
  <%end%>
<%end%>

<%=tag(:br)%>
<%=tag(:br)%>

<%=content_tag :h3, "Invite User by Case ID"%>
<%= form_tag({:controller=>"events", :action=>"send_event_invite"}, method: :post) do %>
  <%= text_field_tag(:case_id) %>
  <%= hidden_field_tag :event, @event%>
  <%= submit_tag 'Invite' %>
  <%if flash[:notice]%>
    <%=content_tag :th, "User does not exist"%>
  <%end%>
<% end %>
<%=tag(:br)%>

<%if @my_rsvp.blank?%>
  <%= link_to "RSVP", rsvp_event_path(@event.id), {method: :patch, class: "button"} %>
  <%=tag(:br)%>
<%end%>

<%=link_to "Events list", events_path%>