config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :friends
    end
    member do
      get :feed
      patch :send_friend_request
    end
  end

  resources :locations do
    collection do
      get :near_me
    end
    member do
      patch :check_in
    end
  end

  resources :indoor_locations

  resources :check_ins

  resources :statistics

  resources :events do
    member do
      post :send_event_invite
      patch :rsvp
    end
  end

  resources :friend_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :invites do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :ratings do
    member do
      patch :upvote
      patch :downvote
    end
  end

  root to: 'users#feed'
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :indoor_location, optional: true
  has_many :ratings

  reverse_geocoded_by :latitude, :longitude

  def <=>(second_location)
    self.score <=> second_location.score
  end

  def score
    self.ratings.pluck(:rating).sum
  end

  def self.selectable_list
    Location.all.map do |location|
       ["#{location.description} (#{location.latitude}, #{location.longitude})", location.id]
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    search = []
    search_params = {}
    indoor_search = false

    if params[:description].present? && params[:description][:filter].present?
      search << "description like :description"
      search_params.merge! description: "%#{params[:description][:filter]}%"
    end

    if params[:building].present? && params[:building][:filter].present?
      search << "building like :building"
      search_params.merge! building: "%#{params[:building][:filter]}%"
      indoor_search = true
    end

    if params[:floor].present? && params[:floor][:filter].present?
      search << "floor like :floor"
      search_params.merge! floor: "%#{params[:floor][:filter]}%"
      indoor_search = true
    end

    if params[:room].present? && params[:room][:filter].present?
      search << "room like :room"
      search_params.merge! room: "%#{params[:room][:filter]}%"
      indoor_search = true
    end

    if indoor_search
      @locations = Location.joins(:indoor_location).includes(:ratings).where(search.join(' AND '), search_params)
    else
      @locations = Location.includes(:ratings).where(search.join(' AND '), search_params)
    end
  end

  def show
    @location = Location.includes(:indoor_location, :ratings).find(params[:id])
    @rating = Rating.where(user_id: session[:cas_user], location_id: params[:id]).first
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.creator_id = session[:cas_user]
    @location.creation_time = DateTime.now
    if @location.save
      redirect_to location_url(@location)
    else
      render action: :new
    end
  end

  def destroy
    Location.find(params[:id]).destroy
    redirect_to locations_url
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(location_params)
      redirect_to location_path(@location)
    else
      render action: :edit
    end
  end

  def check_in
    check_in = CheckIn.new(user_id: session[:cas_user], location_id: params[:id], time: Time.now)
    check_in.save
    redirect_to check_ins_url
  end

  def near_me
    @latitude = params[:latitude].to_f
    @longitude = params[:longitude].to_f

    if @latitude.present? and @longitude.present?
      point = [@latitude, @longitude]
      @locations = Location.near(point, 500, order: false).to_a.sort.reverse
    end
  end

  private

  def location_params
    params.require(:location).permit(:description, :latitude, :longitude, :indoor_location_id)
  end

end

app/views/locations/_form.html.erb
<%=content_tag :table do%>
  <%=content_tag :tr do%>
    <%=content_tag :td do%>
      <%=form.label :description, "Description:"%>
    <%end%>
    <%=content_tag :td do%>
      <%=form.text_field :description%>
    <%end%>
  <%end%>
  <%=content_tag :tr do%>
    <%=content_tag :td do%>
      <%=form.label :latitude, "latitude:"%>
    <%end%>
    <%=content_tag :td do%>
      <%=form.text_field :latitude%>
    <%end%>
  <%end%>
  <%=content_tag :tr do%>
    <%=content_tag :td do%>
      <%=form.label :longitude, "longitude:"%>
    <%end%>
    <%=content_tag :td do%>
      <%=form.text_field :longitude%>
    <%end%>
  <%end%>
  <%=content_tag :tr do%>
    <%=content_tag :td do%>
      <%=form.label :indoor_location_id, "Indoor Location:"%>
    <%end%>
    <%=content_tag :td do%>
      <%=form.select :indoor_location_id, options_for_select(IndoorLocation.selectable_list, @location.indoor_location_id), {include_blank: true}%>
    <%end%>
  <%end%>
<%end%>

app/views/locations/edit.html.erb
<%=content_tag :h1, 'Edit Location'%>
<%=form_for(@location) do |form| %>
  <%=content_tag :table do%>
    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=render partial: 'form', locals:{form:form}%>
      <%end%>
    <%end%>

    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%= tag "input", { "type": "button", "value": "Autopopulate my location", "onclick": "populateLocation(event)" } %>
      <%end%>
    <%end%>

    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=submit_tag "Update"%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

app/views/locations/index.html.erb
<%=content_tag :h1, "Locations"%>

<%=form_tag locations_path, method: :get do%>
  <%=label_tag :description_filter, "Description: "%>
  <%=text_field :description, :filter, value: params[:description].try(:[], :filter)%>
  <%=label_tag :building_filter, "Building: "%>
  <%=text_field :building, :filter, value: params[:building].try(:[], :filter)%>
  <%=label_tag :floor_filter, "Floor: "%>
  <%=text_field :floor, :filter, value: params[:floor].try(:[], :filter)%>
  <%=label_tag :room_filter, "Room: "%>
  <%=text_field :room, :filter, value: params[:room].try(:[], :filter)%>

  <%=submit_tag "Search", id: "search"%>
<%end%>

<%=content_tag :table, class: "colored" do%>
  <%=content_tag :thead do%>
    <%=content_tag :tr do%>
      <%=content_tag :th, "Location id"%>
      <%=content_tag :th, "Score"%>
      <%=content_tag :th, "Description"%>
      <%=content_tag :th, "Latitude, Longitude"%>
      <%=content_tag :th, "Building"%>
      <%=content_tag :th, "Floor"%>
      <%=content_tag :th, "Room"%>
    <%end%>
  <%end%>
  <%=content_tag :tbody do%>
    <%@locations.each do |location|%>
      <%=content_tag :tr do%>
        <%=content_tag :td, link_to(location.id, location)%>
        <%=content_tag :td, location.score%>
        <%=content_tag :td, location.description%>
        <%=content_tag :td, "#{location.latitude}, #{location.longitude}"%>
        <%=content_tag :td, location.indoor_location.try(:building) || "-"%>
        <%=content_tag :td, location.indoor_location.try(:floor) || "-"%>
        <%=content_tag :td, location.indoor_location.try(:room) || "-"%>
        <%if session[:cas_user] == location.creator_id%>
          <%=content_tag :td, link_to("edit", edit_location_path(location))%>
          <%=content_tag :td do%>
            <%=link_to "Delete", location_path(location), data: {confirm: 'Really delete this location?'}, method: :delete%>
          <%end%>
        <%end%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

<%=link_to "New Location", new_location_path%>
<%=content_tag :br%>
<%=link_to "Indoor Locations", indoor_locations_path%>
<%=content_tag :br%>
<%=link_to "Locations Near Me", near_me_locations_path%>

app/views/locations/near_me.html.erb
<%=content_tag :h1, "Best Locations Near Me" %>

<%=content_tag :div, id: "status" do%>
<%end%>

<%if @locations.present?%>
  <%=content_tag :table, class: "colored" do%>
    <%=content_tag :thead do%>
      <%=content_tag :tr do%>
        <%=content_tag :th, "Location ID"%>
        <%=content_tag :th, "Score"%>
        <%=content_tag :th, "Description"%>
        <%=content_tag :th, "Distance"%>
        <%=content_tag :th, "Building"%>
        <%=content_tag :th, "Floor"%>
        <%=content_tag :th, "Room"%>
      <%end%>
    <%end%>
    <%=content_tag :tbody do%>
      <%@locations.each do |location|%>
        <%=content_tag :tr do%>
          <%=content_tag :td, link_to(location.id, location)%>
          <%=content_tag :td, location.score%>
          <%=content_tag :td, location.description%>
          <%=content_tag :td, print_miles(location.distance)%>
          <%=content_tag :td, location.indoor_location.try(:building) || "-"%>
          <%=content_tag :td, location.indoor_location.try(:floor) || "-"%>
          <%=content_tag :td, location.indoor_location.try(:room) || "-"%>
          <%if session[:cas_user] == location.creator_id%>
            <%=content_tag :td, link_to("edit", edit_location_path(location))%>
          <%end%>
        <%end%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

<%=javascript_tag do%>
  function applyCoordinates(position) {
    var lat = position.coords.latitude;
    var long = position.coords.longitude;
    var url = "<%=escape_javascript(near_me_locations_path)%>" + "?latitude=" + lat + "&longitude=" + long;
    window.location.href = url;
  }

  function handleError(error) {
  	if (error.code == 1)
  		var message = "If you don&rsquo;t give us your location, we can&rsquo;t find locations near you! Check your browser for a popup asking for permission.";
  	else {
  		var message = "There was a problem finding your location.";
  	}
  	document.getElementById("status").innerHTML=message;
  }

  <%if params[:latitude].blank? || params[:longitude].blank?%>
    navigator.geolocation.getCurrentPosition(applyCoordinates, handleError, {maximumAge: 0});
    document.getElementById("status").innerHTML="Finding location&hellip;";
  <%end%>

<%end%>

app/views/locations/new.html.erb
<%=content_tag :h1, 'New Location'%>
<%=form_for(@location) do |form| %>
  <%=content_tag :table do%>
    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=render partial: 'form', locals:{form:form}%>
      <%end%>
    <%end%>

    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%= tag "input", { "type": "button", "value": "Autopopulate my location", "onclick": "populateLocation(event)" } %>
      <%end%>
    <%end%>

    <%=content_tag :tr do%>
      <%=content_tag :td do%>
        <%=submit_tag "Create"%>
      <%end%>
    <%end%>
  <%end%>
<%end%>

app/views/locations/show.html.erb
<%=content_tag :h1, "Location"%>

<%=content_tag :table, class: "key-value" do%>
  <%=content_tag :tr do%>
    <%=content_tag :th, "ID"%>
    <%=content_tag :td, @location.id%>
  <%end%>

  <%=content_tag :tr do%>
    <%=content_tag :th, "Description"%>
    <%=content_tag :td, @location.description%>
  <%end%>

  <%=content_tag :tr do%>
    <%=content_tag :th, "Coordinates"%>
    <%=content_tag :td, "#{@location.latitude}, #{@location.longitude}"%>
  <%end%>

  <%if @location.indoor_location.present?%>
    <%=content_tag :tr do%>
      <%=content_tag :th, "Building"%>
      <%=content_tag :td, @location.indoor_location.building%>
    <%end%>

    <%=content_tag :tr do%>
      <%=content_tag :th, "Floor"%>
      <%=content_tag :td, @location.indoor_location.floor%>
    <%end%>

    <%=content_tag :tr do%>
      <%=content_tag :th, "Room"%>
      <%=content_tag :td, @location.indoor_location.room%>
    <%end%>
  <%end%>

  <%=content_tag :tr do%>
    <%=content_tag :th, "Score"%>
    <%=content_tag :td, @location.score%>
  <%end%>

<%end%>


<%=@rating.try(:positive?) ? "Upvoted" : (link_to "Upvote", upvote_rating_path(@location), {method: :patch, class: "button"})%>
<%=@rating.try(:negative?) ? "Downvoted" : (link_to "Downvote", downvote_rating_path(@location), {method: :patch, class: "button"})%>

<%=content_tag(:br)%>
<%=link_to("Check In", check_in_location_path(@location), {method: :patch, class: "button"})%>

<%=content_tag(:br)%>
<%=link_to "Location List", locations_path%>