config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :friends
    end
    member do
      get :feed
      patch :send_friend_request
    end
  end

  resources :locations do
    collection do
      get :near_me
    end
    member do
      patch :check_in
    end
  end

  resources :indoor_locations

  resources :check_ins

  resources :statistics

  resources :events do
    member do
      post :send_event_invite
      patch :rsvp
    end
  end

  resources :friend_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :invites do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :ratings do
    member do
      patch :upvote
      patch :downvote
    end
  end

  root to: 'users#feed'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaCWRUmosa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <%=content_tag :h1, link_to("LaCWRUmosa", root_path)%>

        <%=content_tag :ul do%>
          <%=content_tag :li, link_to("Friends", friends_users_path)%>
          <%=content_tag :li, link_to(print_with_count("Friend Requests", @pending_friend_request_count), friend_requests_path)%>
          <%=content_tag :li, link_to("Locations", locations_path)%>
          <%=content_tag :li, link_to("Check Ins", check_ins_path)%>
          <%=content_tag :li, link_to("Events", events_path)%>
          <%=content_tag :li, link_to(print_with_count("Invitations", @pending_invitation_count), invites_path)%>
        <%end%>
      </nav>
    </header>
    <article>
      <%= yield %>
    </article>
  </body>
</html>